language: node_js
sudo: required
dist: trusty
addons:
  firefox: "latest"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - oracle-java8-installer
env:
  - CXX=g++-4.8
node_js:
  - 6
jdk:
  - oraclejdk8
before_script:
  - npm run build
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm run serve-static &
  - sleep 10 # give xvfb some time to start
script: npm run lint && npm run coverage && npm run e2e-test -- --env travis
